# Generated by Django 3.1.5 on 2021-01-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210121_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(default=1, editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
