# Generated by Django 3.1.5 on 2021-01-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_instructor',
            field=models.BooleanField(default=True),
        ),
    ]
