# Generated by Django 3.1.5 on 2021-01-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20210113_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='card_description',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_description',
            field=models.TextField(default='', max_length=512),
        ),
    ]
