# Generated by Django 3.1.5 on 2021-01-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20210113_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='card_description',
            field=models.TextField(blank=True, default='', max_length=256, null=True),
        ),
    ]
