# Generated by Django 3.1.5 on 2021-01-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20210115_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lesson_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
