version: '3.8'

services:
  web:
    build: .
    command: gunicorn yoga.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    container_name: postgres_database_for_yoga_app
    image: postgres:13.0-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env.prod.db

volumes:
  postgres_data:

