# Generated by Django 3.1.5 on 2021-01-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20210107_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='card_description',
            field=models.TextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
