# Generated by Django 3.1.5 on 2021-01-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_auto_20210108_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson_images/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessonimage', to='lessons.lesson')),
            ],
        ),
    ]
