# Generated by Django 3.1.5 on 2021-01-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_auto_20210118_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonitem',
            name='paid_for',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
