# Generated by Django 3.1.5 on 2021-01-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_auto_20210118_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonreview',
            name='rating',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
