# Generated by Django 3.1.5 on 2021-01-19 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_auto_20210119_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonreview',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
