# Generated by Django 3.1.5 on 2021-02-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0031_auto_20210208_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='yoga_style',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
