# Generated by Django 3.1.5 on 2021-02-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0033_remove_subscription_paid_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
