# Generated by Django 3.1.5 on 2021-02-09 13:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0034_auto_20210209_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default=1, force_format='JPEG', keep_meta=True, quality=75, size=[600, 600], upload_to='lesson_images/'),
            preserve_default=False,
        ),
    ]
