# Generated by Django 3.1.5 on 2021-02-17 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0035_auto_20210209_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonreview',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
