# Generated by Django 3.1.5 on 2021-01-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20210106_0938'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='InstructorProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
