# Generated by Django 3.1.5 on 2021-01-13 08:13

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210113_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[600, 600], upload_to='profile_images/'),
        ),
    ]
