# Generated by Django 3.1.5 on 2021-02-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_userprofile_lesson_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='card_description',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
    ]
