# Generated by Django 3.1.5 on 2021-02-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210122_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='sales_percentage',
            field=models.PositiveSmallIntegerField(default=30, editable=False),
        ),
    ]
