# Generated by Django 3.1.5 on 2021-01-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20210106_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='name',
            new_name='lesson_name',
        ),
    ]
