# Generated by Django 3.1.5 on 2021-01-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20210106_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='instructor_name',
            new_name='instructor_profile',
        ),
    ]
