# Generated by Django 3.1.5 on 2021-01-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20210107_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='yoga_style',
            field=models.CharField(default='Yoga', max_length=50),
        ),
    ]
