# Generated by Django 3.1.5 on 2021-01-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_lessonimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='card_description',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(max_length=512),
        ),
    ]
