# Generated by Django 3.1.5 on 2021-01-18 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20210115_1125'),
        ('lessons', '0017_auto_20210118_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=512)),
                ('rating', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewedLesson', to='lessons.lesson')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='profiles.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='LessonImages',
        ),
    ]
