# Generated by Django 3.1.5 on 2021-01-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0024_auto_20210128_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
