# Generated by Django 3.1.5 on 2021-01-30 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_userprofile_lesson_count'),
        ('lessons', '0027_auto_20210129_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonReviewFlagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileThatFlaggedReview', to='profiles.userprofile')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flaggedReview', to='lessons.lessonreview')),
            ],
        ),
    ]
