# Generated by Django 3.1.5 on 2021-02-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0028_lessonreviewflagged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonreviewflagged',
            options={'verbose_name_plural': 'Lesson Reviews Flagged'},
        ),
    ]
