# Generated by Django 3.1.5 on 2021-02-22 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0037_auto_20210217_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonreview',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
